kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: podkeeper
subjects:
- kind: ServiceAccount
  name: podkeeper
roleRef:
  kind: Role
  name: podkeeper
  apiGroup: rbac.authorization.k8s.io
